PROGRAM -> FUNCTIONS

FUNCTIONS -> FUNCTION FUNCTIONS
FUNCTIONS -> EMPTY

FUNCTION -> FUNTION_KEYWORD RETURN_TYPE BINDING_OPERATOR FUNCTION_IDENTIFIER LEFT_PARENTHESES FUNCTION_PARAMETERS RIGHT_PARENTHESES LEFT_FLOWER_BRACKET COMPOUND_STATEMENTS RIGHT_FLOWER_BRACKET END_DEFINITION_KEYWORD

FUNCTION_PARAMETERS -> PARAMETERS
FUNCTION_PARAMETERS -> VOID_KEYWORD
PARAMETERS -> PARAMETER MORE_PARAMETERS
MORE_PARAMETERS -> COMMA_SEPARATOR PARAMETERS
MORE_PARAMETERS -> EMPTY
PARAMETER -> DATA_TYPE BINDING_OPERATOR IDENTIFIER

COMPOUND_STATEMENTS -> STATEMENT COMPOUND_STATEMENTS
COMPOUND_STATEMENTS -> EMPTY

STATEMENT -> LOOP_STATEMENT
STATEMENT -> CONDITIONAL_STATEMENTS
STATEMENT -> BREAK_STATEMENTS SEMI_COLON_SEPARATOR
STATEMENT -> FUNCTION_CALL SEMI_COLON_SEPARATOR
STATEMENT -> INITIALIZATION_STATEMENTS SEMI_COLON_SEPARATOR

LOOP_STATEMENT -> WHILE_KEYWORD LEFT_PARENTHESES LOGICAL_EXPRESSION RIGHT_PARENTHESES LEFT_FLOWER_BRACKET COMPOUND_STATEMENTS RIGHT_FLOWER_BRACKET END_KEYWORD

CONDITIONAL_STATEMENTS -> IF_KEYWORD LEFT_PARENTHESES LOGICAL_EXPRESSION RIGHT_PARENTHESES LEFT_FLOWER_BRACKET COMPOUND_STATEMENTS RIGHT_FLOWER_BRACKET ELSE_STATEMENT
ELSE_STATEMENT -> ELSE_KEYWORD LEFT_FLOWER_BRACKET COMPOUND_STATEMENTS RIGHT_FLOWER_BRACKET
ELSE_STATEMENT -> EMPTY

BREAK_STATEMENTS -> BREAK_KEYWORD
BREAK_STATEMENTS -> CONTINUE_KEYWORD
BREAK_STATEMENTS -> RETURN_KEYWORD RETURN_ENTITY
RETURN_ENTITY -> EXPRESSION
RETURN_ENTITY -> VOID_KEYWORD

FUNCTION_CALL -> FUNCTION_IDENTIFIER LEFT_PARENTHESES ARGUEMENTS RIGHT_PARENTHESES

ARGUEMENTS -> VOID_KEYWORD
ARGUEMENTS -> TERMIMAL_EXPRESSION ADDITIONAL_ARGUMENTS
ADDITIONAL_ARGUMENTS -> COMMA_SEPARATOR ARGUEMENTS
ADDITIONAL_ARGUMENTS -> EMPTY

INITIALIZATION_STATEMENTS -> DATA_TYPE BINDING_OPERATOR TERMINAL_ID ASSIGN_STATEMENT
INITIALIZATION_STATEMENTS -> TERMINAL_ID ASSIGNMENT_OPERATOR EXPRESSION
ASSIGN_STATEMENT -> ASSIGNMENT_OPERATOR EXPRESSION
ASSIGN_STATEMENT -> EMPTY

TERMIMAL_EXPRESSIONS -> TERMIMAL_EXPRESSION ADDITIONAL_TERMINALS
ADDITIONAL_TERMINALS -> COMMA_SEPARATOR TERMIMAL_EXPRESSIONS
ADDITIONAL_TERMINALS -> EMPTY

EXPRESSION -> LOGICAL_EXPRESSION
LOGICAL_EXPRESSION -> RELATIONAL_EXPRESSION

RELATIONAL_EXPRESSION -> LEFT_PARENTHESES RELATIONAL_EXPRESSION RIGHT_PARENTHESES RELATION_OPERATION
RELATION_OPERATION -> REL_OP LEFT_PARENTHESES RELATIONAL_EXPRESSION RIGHT_PARENTHESES
RELATION_OPERATION -> EMPTY

RELATIONAL_EXPRESSION -> NUMERIC_EXPRESSION MORE_REL_OP
MORE_REL_OP -> REL_OP NUMERIC_EXPRESSION
MORE_REL_OP -> EMPTY

NUMERIC_EXPRESSION -> MULTIPLICATION_EXPRESSION NUMERIC_OPERATION
NUMERIC_OPERATION -> ADDITION_OPERATOR MULTIPLICATION_EXPRESSION
NUMERIC_OPERATION -> SUBTRACTION_OPERATOR MULTIPLICATION_EXPRESSION
NUMERIC_OPERATION -> EMPTY

MULTIPLICATION_EXPRESSION -> TERMIMAL_EXPRESSION MULTIPLICATION_OPERATION
MULTIPLICATION_OPERATION -> MULTIPLICATION_OPERATOR TERMIMAL_EXPRESSION
MULTIPLICATION_OPERATION -> DIVISION_OPERATOR TERMIMAL_EXPRESSION
MULTIPLICATION_OPERATION -> MODULO_OPERATOR TERMIMAL_EXPRESSION
MULTIPLICATION_OPERATION -> EMPTY

REL_OP -> REL_EQ_OP
REL_OP -> REL_INEQ_OP
REL_EQ_OP -> INEQUALITY_OPERATOR
REL_EQ_OP -> EQAULITY_OPERATOR
REL_INEQ_OP -> GREATER_THAN_EQUAL_OPERATOR
REL_INEQ_OP -> LESS_THAN_EQUAL_OPERATOR
REL_INEQ_OP -> GREATER_THAN_OPERATOR
REL_INEQ_OP -> LESS_THAN_OPERATOR

TERMIMAL_EXPRESSION -> TERMINAL_ID
TERMIMAL_EXPRESSION -> FUNCTION_CALL
TERMIMAL_EXPRESSION -> INTEGER
TERMINAL_ID -> IDENTIFIER

RETURN_TYPE -> DATA_TYPE
RETURN_TYPE -> VOID_KEYWORD

DATA_TYPE -> BOOLEAN_KEYWORD
DATA_TYPE -> INTEGER_KEYWORD

BOOLEAN -> TRUE_KEYWORD
BOOLEAN -> FALSE_KEYWORD

INTEGER -> POSITIVE_INTEGER
INTEGER -> NEGATIVE_INTEGER
NEGATIVE_INTEGER -> SUBTRACTION_OPERATOR POSITIVE_INTEGER
